[package]
name = "wl-mirror-gui"
version = "0.1.0"
authors = ["merelymyself/pwygab"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
iced = "0.6.0"
iced_aw = { version = "0.2", default-features = false, features = ["number_input"] }
tracing-subscriber = "0.3"
