[package]
name = "wl-mirror-gui"
version = "0.1.0"
authors = ["merelymyself/pwygab"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
eframe = "0.20.1"
winit = "0.27.5"
tracing-subscriber = "0.3"
